## Indexing, Slicing, Reshaping, Joining, and Spiliting the array in Python


In [5]:
import numpy as np
x = np.random.randint(10, size = 6)
print("x ndim:",x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)
print("x data",x.dtype)
print("x itemsize:", x.itemsize)
print("x nbytes", x.nbytes)


x ndim: 1
x shape: (6,)
x size: 6
x data int32
x itemsize: 4
x nbytes 24


In [6]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[5::-2])

[5 3 1]


In [8]:
x2 = np.array([[12,5,3],[7,6,8]])
print(x2[::-1,::-1])

[[ 8  6  7]
 [ 3  5 12]]


In [10]:
x3 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
print(x3[:2,:3])

[[12  5  2]
 [ 7  6  8]]


In [27]:
import numpy as np #import the numpy 
x1 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7],[1,2,4,6],[1,1,2,3]])  #define the array
print(x1)
print('\n')
print("x1",x1[:,0])
print('\n')
print("x",x1[:2,:2])
print('\n')
print(x1[:2,:2].copy())
print('\n')
x3=x1[:2,:2]
print("X3",x3)
print('\n')
#Eneter the value on [0,0]
x3[0,0]=92
print(x3)
print('\n')
#Reshapre the array
grid = np.arange(1,10).reshape((3,3))
print(grid)
print('\n')
#another method to reshape the array
print("R",x1[:,np.newaxis])
print('\n')
x = [1,2,3,4,5,6,8]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)
print('\n')

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]
 [ 1  2  4  6]
 [ 1  1  2  3]]


x1 [12  7  1  1  1]


x [[12  5]
 [ 7  6]]


[[12  5]
 [ 7  6]]


X3 [[12  5]
 [ 7  6]]


[[92  5]
 [ 7  6]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


R [[[92  5  2  4]]

 [[ 7  6  8  8]]

 [[ 1  6  7  7]]

 [[ 1  2  4  6]]

 [[ 1  1  2  3]]]


[1 2 3] [4 5] [6 8]




In [1]:
import numpy as np
a = np.array((1,2,3))
print(a)

print("\n")
a = np.array([(1,2,3),(4,5,6)])
print(a)
print("\n")

import sys
s = range(1000)
print(sys.getsizeof(5)*len(s))
D = np.arange(1000)
print(D.size*D.itemsize)

[1 2 3]


[[1 2 3]
 [4 5 6]]


28000
4000
