In [1]:
import numpy as np
arr = np.array([1.2,4.5,6.4])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 4 6]
int32


In [2]:
a = np.array([1,2,3,4,5])
x = a.copy()
a[0] = 23
print(a)
print(x)

[23  2  3  4  5]
[1 2 3 4 5]


In [3]:
a = np.array([1,2,3,4,5])
x = a.view()
a[0] = 23
print(a)
print(x)

[23  2  3  4  5]
[23  2  3  4  5]


In [4]:
print(a.shape)

(5,)


In [5]:
aa = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newa = aa.reshape(3,4)
print(newa)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
aa = np.array([[1,2,3],[4,5,6]])
newa = aa.reshape(3,2)
print(newa)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
for x in aa:
    print(x)

[1 2 3]
[4 5 6]


In [13]:
for x in aa:
    for y in x:
        print(y)

1
2
3
4
5
6


In [14]:
for x in np.nditer(aa):
    print(x)

1
2
3
4
5
6


In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [22]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[6,7]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 4 5]
 [3 4 6 7]]


In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
