In [1]:
x = 5
y = "john"
print(x)
print(y)

5
john


In [2]:
a = 10
A = 20
print(a)
print(A)

10
20


In [3]:
a= int(input("Enter the number"))
print(a)

Enter the number34
34


In [4]:
x,y,z ="ABC",4,5.6
print(x)
print(y)
print(z)

ABC
4
5.6


In [5]:
fruits = ["apple","banana","cherry"]
x,y,z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


In [14]:
b = int(5)
c = int(4)
d = c + b
print("The sum of %d", b)

The sum of %d 5


In [17]:
a = 10
b = 20
def func():
    a = 100
    global b
    b = 200
    print("Inside value of a is",a,"and b is:",b)
func()
print("Outside value of a is:",a,"and b is:",b)

Inside value of a is 100 and b is: 200
Outside value of a is: 10 and b is: 200


In [3]:
import numpy as np
a = np.array((1,2,3))
print(a)

[1 2 3]


In [4]:
a = np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [28]:
# import sys
s = range(1000)
print(sys.getsizeof(5)*len(s))
D = np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [8]:
import time
SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
start = time.time()
result = A1 + A2
# print("\n")
print((time.time()-start)*1000)

0.0
0.0


In [9]:
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [10]:
a = np.array([(1,2,3),(4,5,6)])
print(a.itemsize)

4


In [13]:
print(a.dtype)

int32


In [14]:
print(a.size)
print(a.shape)

3
(1, 3)


In [33]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [23]:
print(c[0,2])

3


In [35]:
print(c[1:,2])

[6]


In [38]:
b=np.array([(8,9),(10,11),(12,13)])
print(b[0:2,1])

[ 9 11]


In [43]:
aa=np.linspace(0,2,2)
print(aa)

[0. 2.]


In [42]:
a = np.array([1,2,3])
print(a.max())
print(a.min())
print(a.sum())

3
1
6


In [47]:
print(c)
print(c.sum(axis=0))
print(c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [48]:
print(np.sqrt(c))
print(np.std(c))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [51]:
d=np.array([(1,2,3),(3,4,5)])
print(c)
print(d)
print(np.vstack((c,d)))
print(np.hstack((c,d)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [4 5 6 3 4 5]]


In [52]:
print(c.ravel())

[1 2 3 4 5 6]
