In [18]:
import numpy as np
myArray = np.array([10,20,30,40,50])
print(myArray)
print("Type of Array",type(myArray))
print("Size of Array is",myArray.size)
print("Shape of Array is",myArray.shape)
print("Dimension of Array is:",myArray.ndim)
sum = 0
for i in myArray:
    sum = sum + i
print("Sum of Array is: ",sum)
print("Maximum element is:",max(myArray))
print("Minimum element is:",min(myArray))
num = int(input("Enter the number"))
if num in myArray:
    print("Found")
else:
    print("Not Found")

[10 20 30 40 50]
Type of Array <class 'numpy.ndarray'>
Size of Array is 5
Shape of Array is (5,)
Dimension of Array is: 1
Sum of Array is:  150
Maximum element is: 50
Minimum element is: 10
Enter the number24
Not Found


In [20]:
import numpy as np
class operation:
    def operationusingfun():
        myarray = [12,13,14,15,16,17]
        return myarray
d = operation()
print(d.operationusingfun)

<bound method operation.operationusingfun of <__main__.operation object at 0x00000273EFCF8E20>>


In [21]:
import numpy as np
myArray = np.array([10,20,30,40,50,60,70,80])
print(myArray)
print(myArray.ndim)
myarray = myArray.reshape(2,4)
print(myarray)
print(myarray.ndim)
print(myarray.size)
print(myarray.shape)

[10 20 30 40 50 60 70 80]
1
[[10 20 30 40]
 [50 60 70 80]]
2
8
(2, 4)


In [16]:
import numpy as np
myArray = np.array([10,20,30,40])
myArray2 = np.array([50,60,70,80])
print(myArray)
print(myArray2)
myArray3 = np.append(myArray,myArray2)
print(myArray3)

[10 20 30 40]
[50 60 70 80]
[10 20 30 40 50 60 70 80]


In [23]:
import numpy as np
myArray = np.array([10,20,30,40])
myArray2 = np.array([50,60,70,80])
myArray3 = myArray + myArray
print(myArray3)

[20 40 60 80]


In [30]:
import numpy as np
matrix1 = [
      [1, 2, 3], [4, 5, 6], [7, 8, 9]
   ] 
matrix2 = [
      [7, 8, 9], [4, 5, 6],[1, 2, 3]
   ]
print(matrix1)
print(matrix2)
result = np.dot(matrix1, matrix2)
print(result)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]
[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [34]:
import numpy as np
myArray = np.array([1,2])
myArray2 = np.array([5,6])
print(myArray)
print(myArray2)
result = np.dot(myArray,myArray2)
print(result)

[1 2]
[5 6]
17
